### ISSUE TITLE
chrome显示The app does not get QQ login permission.

### ISSUE THREAD

**Issue by imcake** [liujiao111/map-easygo#1]
双击bat运行后，会出现三次chrome窗口，然后窗口显示的是The app does not get QQ login permission. 然后就pause了

![Snipaste_2019-07-02_21-27-16](https://user-images.githubusercontent.com/3276093/60516611-af718200-9d10-11e9-8f4c-97c190df2093.png)

cmd窗口显示代码如下
```
E:\tmp\map-easygo>python3 ./main.py
2019-07-02 21:26:59此轮抓取开始

DevTools listening on ws://127.0.0.1:12432/devtools/browser/33eaa43a-6a11-4659-bbe9-87fb450d3292

DevTools listening on ws://127.0.0.1:12315/devtools/browser/6bb15981-46ec-45d5-bf7b-96569dda35ae

DevTools listening on ws://127.0.0.1:12539/devtools/browser/8aee208b-6df1-4514-9b88-f80a2a991959

Traceback (most recent call last):
  File "./main.py", line 83, in get_cookie
    qq_ = self.qq_number_list.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./main.py", line 212, in <module>
    app.exec()
  File "./main.py", line 174, in exec
    cookie = self.get_cookie()
  File "./main.py", line 86, in get_cookie
    qq_ = self.qq_number_list.pop()
IndexError: pop from empty list
```

**Comment by NoIdea124** [comment]
同上

**Comment by luliangdang** [comment]
同上

**Comment by zhangchu0760** [comment]
同上

**Comment by zilin-guo** [comment]
同上

**Comment by xiantuteng** [comment]
腾讯已经封了QQ登录接口，只能使用微信登录

**Comment by zhangchu0760** [comment]
> 腾讯已经封了QQ登录接口，只能使用微信登录

请问现在怎么解决呢？

**Comment by xiantuteng** [comment]
> > 腾讯已经封了QQ登录接口，只能使用微信登录
> 
> 请问现在怎么解决呢？
使用微信来登录。

采用域名欺骗的方式完成腾讯宜出行采集框架。思路如下：
1. 将宜出行的前端页面下载到本地，搭建纯静态网站；
2. 使用Nginx反向代理宜出行的所有API，
3. 修改本机hosts文件，为本机IP增加宜出行的域名解析 
127.0.0.1 c.easygo.qq.com
4. 使用Nginx代理，将前端请求解析到本机的纯静态网站，将宜出行接口代理到腾讯宜出行接口的IP地址；

	upstream eg-toc {
		server 183.61.38.179;
        } 
	server {
		listen 80;
		server_name c.easygo.qq.com;
		location ^~ /api/ {
			proxy_pass  http://eg-toc; 
			proxy_redirect     off;
			proxy_set_header   Host             $host:$server_port;
			proxy_set_header   X-Real-IP        $remote_addr;
			proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
			proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
			proxy_max_temp_file_size 0;
			proxy_connect_timeout   30;  
			proxy_send_timeout      30;  
			proxy_read_timeout      30;  
		}
		location / {
			root    html/qq-map;
			index   index.html;
			try_files   $uri /index.html;
		}
	}


5. 修改本机的纯静态网站的JS文件，将每次请求热力图数据的结果上传到指定的网站。
主要是修改 map-d76c21c16d.bundle.js 这个文件。找到 /egc/heatmapdata 这个接口访问的地址，把Ajax请求后的数据再上传到自己写的接口。
6. 在微信访问链接：http://c.easygo.qq.com/eg_toc/map.html

这样访问微信访问后，就会将势力图的数据自动上传到自己的接口中。

**Comment by cswxin** [comment]
selenium模拟QQ空间登录然后再打开宜出行
